// Sample data (you can replace this with your data)
var directoryData = [
    {
      "Title": "La Vicenta | Restaurante de carnes en Cancún",
      "tags": "fine dining",
      "Likes": 4.5,
      "topLeftText": "+52 998 688 6736",
      "description": "Av. Bonampak MZ 2",
      "modalDescription": "Av. Bonampak MZ 2 - Upscale steakhouse offering premium cuts and an extensive wine list",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77504,
      "linkUrl": "http://lavicenta.com.mx/"
    },
    {
      "Title": "Va q' Va!!!",
      "tags": "street food",
      "Likes": 4.4,
      "topLeftText": "+52 998 255 7435",
      "description": "C. 107 Manzana 38 Lote 18 y 19",
      "modalDescription": "C. 107 Manzana 38 Lote 18 y 19 - Authentic Mexican street food experience",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77517,
      "linkUrl": "http://vaqva.com.mx/"
    },
    {
      "Title": "La Bamba \"Mex-Seafood\"",
      "tags": "restaurant",
      "Likes": 4.8,
      "topLeftText": "+52 998 487 5503",
      "description": "Blvd. Kukulcan Km 9.5",
      "modalDescription": "Blvd. Kukulcan Km 9.5 - Fresh seafood with Mexican flavors",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/889429451402064/"
    },
    {
      "Title": "El Café Mexicano",
      "tags": "cafe",
      "Likes": 4.7,
      "topLeftText": "+52 998 881 0808",
      "description": "Rtno. del Rey 36",
      "modalDescription": "Rtno. del Rey 36 - Cozy cafe serving Mexican coffee and pastries",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.kempinski.com/"
    },
    {
      "Title": "The White Box",
      "tags": "fine dining",
      "Likes": 4.6,
      "topLeftText": "",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan - Contemporary fine dining with ocean views",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://oasishoteles.com/en/restaurants/the-white-box"
    },
    {
      "Title": "LA DOÑA CANCUN",
      "tags": "restaurant",
      "Likes": 4.2,
      "topLeftText": "+52 998 209 1457",
      "description": "Traditional Mexican Restaurant",
      "modalDescription": "Traditional Mexican cuisine in a warm atmosphere",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/pages/La-Doña/557605110934240"
    },
    {
      "Title": "TACO y TEQUILA",
      "tags": "bar",
      "Likes": 4.3,
      "topLeftText": "+52 998 176 8099",
      "description": "Blvd. Kukulcan 25",
      "modalDescription": "Blvd. Kukulcan 25 - Mexican bar with extensive tequila selection",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.tacoytequila.com/"
    },
    {
      "Title": "Cocos and Grill",
      "tags": "bar",
      "Likes": 4.4,
      "topLeftText": "+52 998 849 5899",
      "description": "Beach Bar & Grill",
      "modalDescription": "Beachfront bar and grill with tropical cocktails",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.cocosandgrill.com.mx/"
    },
    {
      "Title": "Elefanta",
      "tags": "restaurant",
      "Likes": 4.5,
      "topLeftText": "+52 998 144 0364",
      "description": "Blvd. Kukulcan Km 12.5",
      "modalDescription": "Blvd. Kukulcan Km 12.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.elefanta.com.mx/"
    },
    {
      "Title": "Tora | Japanese Restaurant in Cancun",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "+52 998 313 4128",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://torarestaurant.com.mx/es/sucursales/restaurante-en-cancun?utm_source=google&utm_medium=organic&utm_campaign=GMB_reservas"
    },
    {
      "Title": "El Timón De Cancún",
      "tags": "restaurant",
      "Likes": 4.3,
      "topLeftText": "+52 998 478 4809",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://eltimondecancun.com/"
    },
    {
      "Title": "Taquería el Poblano",
      "tags": "street food",
      "Likes": 4.3,
      "topLeftText": "+52 998 884 2495",
      "description": "Av Tulum 65",
      "modalDescription": "Av Tulum 65 - Authentic street tacos and Mexican antojitos",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://elpoblano.restaurantwebexperts.com/"
    },
    {
      "Title": "El Café Mexicano",
      "tags": "restaurant",
      "Likes": 4.7,
      "topLeftText": "+52 998 881 0808",
      "description": "Rtno. del Rey 36",
      "modalDescription": "Rtno. del Rey 36",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.kempinski.com/en/hotel-cancun/restaurants-bars/el-cafe-mexicano?utm_medium=organic&utm_source=google&utm_campaign=KICUN1&utm_content=gmb&source=S308962248"
    },
    {
      "Title": "Captain's Cove",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "+52 998 885 0016",
      "description": "Blvd. Kukulcan KM16.5",
      "modalDescription": "Blvd. Kukulcan KM16.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://captainscoverestaurant.com/"
    },
    {
      "Title": "Gustino Italian Grill",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.gustinocancun.com/?scid=bb1a189a-fec3-4d19-a255-54ba596febe2&y_source=1_NTYyMTM5Ni03MTUtbG9jYXRpb24uZ29vZ2xlX3dlYnNpdGVfb3ZlcnJpZGU="
    },
    {
      "Title": "Harry's Steakhouse & Raw Bar | Cancun",
      "tags": "restaurant",
      "Likes": 4.8,
      "topLeftText": "+52 998 840 6554",
      "description": "Kukulkan 1",
      "modalDescription": "Kukulkan 1",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://harrys.com.mx/?utm_source=Website&utm_medium=Ficha&utm_campaign=Local"
    },
    {
      "Title": "The Surfin Burrito",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "+52 998 883 0083",
      "description": "Kukulkan Km. 9.5",
      "modalDescription": "Kukulkan Km. 9.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.facebook.com/thesurfinburrito"
    },
    {
      "Title": "Navíos",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 885 3848",
      "description": "Blvd. Kukulcan Km. 19.5",
      "modalDescription": "Blvd. Kukulcan Km. 19.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.naviosseafood.com/"
    },
    {
      "Title": "El Rincon de los Antojos",
      "tags": "restaurant",
      "Likes": 4.3,
      "topLeftText": "",
      "description": "Calle Luciérnaga 365",
      "modalDescription": "Calle Luciérnaga 365",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.elrincondelosantojos.com/"
    },
    {
      "Title": "Carajillo Cancun | Mexican Cuisine & Entertainment",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "+52 998 626 9070",
      "description": "Blvd. Kukulcan Km. 14.7",
      "modalDescription": "Blvd. Kukulcan Km. 14.7",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.carajillomx.com/"
    },
    {
      "Title": "Ramona Mexican Restaurant",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 891 5700",
      "description": "Punta Nizuc - Cancún km 7.5",
      "modalDescription": "Punta Nizuc - Cancún km 7.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.nizuc.com/cuisine/ramona/"
    },
    {
      "Title": "Kultura | by Athinagoras Kostakos",
      "tags": "restaurant",
      "Likes": 4.3,
      "topLeftText": "+52 998 167 3652",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.kulturarestaurant.com.mx/restaurantes-cancun"
    },
    {
      "Title": "Pescaditos",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "+52 998 884 0305",
      "description": "Av Yaxchilán 69",
      "modalDescription": "Av Yaxchilán 69",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://pescaditos.restaurantsnapshot.com/"
    },
    {
      "Title": "The Caribbean galleon",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "",
      "description": "Kukulkan ",
      "modalDescription": "Kukulkan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/elgaleondelcaribe/"
    },
    {
      "Title": "Dons Tacos and Burritos",
      "tags": "restaurant",
      "Likes": 4.5,
      "topLeftText": "+52 998 234 2550",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.donstaco.com/"
    },
    {
      "Title": "EL GRANERO GRILL & DRINKS",
      "tags": "restaurant",
      "Likes": 4.3,
      "topLeftText": "+52 998 378 4191",
      "description": "Blvd. Kukulcan Mz 48 Lt 6",
      "modalDescription": "Blvd. Kukulcan Mz 48 Lt 6",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://granerogrillcancun.com/"
    },
    {
      "Title": "Restaurante Los Alcatraces",
      "tags": "restaurant",
      "Likes": 4.5,
      "topLeftText": "+52 998 884 3918",
      "description": "C. 5 Alcatraces 31",
      "modalDescription": "C. 5 Alcatraces 31",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://loshuaraches.restaurantwebexperts.com/"
    },
    {
      "Title": "Peter's Restaurante",
      "tags": "restaurant",
      "Likes": 4.8,
      "topLeftText": "+52 998 251 9310",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/pages/PETERs-Restaurante/142777445759785"
    },
    {
      "Title": "Nicoletta | Italian restaurant in Cancun",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 251 6513",
      "description": "Blvd. Kukulcan Km. 13.5",
      "modalDescription": "Blvd. Kukulcan Km. 13.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://nicolettarestaurant.com/es/cancun/"
    },
    {
      "Title": "Que Gorditas...!",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 898 2263",
      "description": "Av Yaxchilán 65",
      "modalDescription": "Av Yaxchilán 65",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77509,
      "linkUrl": "http://restaurantsnapshot.com/quegorditas/"
    },
    {
      "Title": "Fred's | The best seafood in Cancun",
      "tags": "restaurant",
      "Likes": 4.7,
      "topLeftText": "+52 998 251 6535",
      "description": "Blvd. Kukulcan 14.5",
      "modalDescription": "Blvd. Kukulcan 14.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://fredshouserestaurant.com/"
    },
    {
      "Title": "Puerto Madero Cancún",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 885 2829",
      "description": "Blvd. Kukulcan Km. 14.1",
      "modalDescription": "Blvd. Kukulcan Km. 14.1",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.puertomaderorestaurantes.com/"
    },
    {
      "Title": "Hacienda Sisal",
      "tags": "restaurant",
      "Likes": 4.5,
      "topLeftText": "+52 800 020 4680",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://haciendasisal.com/"
    },
    {
      "Title": "Lorenzillo's",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 883 1254",
      "description": "Blvd. Kukulcan Km 10.5",
      "modalDescription": "Blvd. Kukulcan Km 10.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.lorenzillos.com.mx/"
    },
    {
      "Title": "La Bamba Mex-Seafood",
      "tags": "restaurant",
      "Likes": 4.8,
      "topLeftText": "+52 998 487 5503",
      "description": "Blvd. Kukulcan Km 9.5",
      "modalDescription": "Blvd. Kukulcan Km 9.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/889429451402064/"
    },
    {
      "Title": "The Club Grill",
      "tags": "restaurant",
      "Likes": 4.9,
      "topLeftText": "",
      "description": "Rtno. del Rey 36",
      "modalDescription": "Rtno. del Rey 36",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.kempinski.com/en/hotel-cancun/restaurants-bars/the-club-grill?utm_medium=organic&utm_source=google&utm_campaign=KICUN1&utm_content=gmb&source=S308962248"
    },
    {
      "Title": "RosaNegra | Latin American Restaurant in Cancun",
      "tags": "restaurant",
      "Likes": 4.5,
      "topLeftText": "+52 998 313 4132",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://rosanegra.com.mx/es/sucursales/cancun?utm_source=google&utm_medium=organic&utm_campaign=GMB_web"
    },
    {
      "Title": "Porfirio's Cancún | Restaurante de comida mexicana",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 840 6040",
      "description": "Blvd. Kukulcan A",
      "modalDescription": "Blvd. Kukulcan A",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://porfirios.com.mx/locaciones/restaurante-mexicano-en-cancun/"
    },
    {
      "Title": "Taboo | Mediterranean Restaurant in Cancun",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "+52 998 234 2528",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://www.taboorestaurant.com.mx/restaurantes-cancun"
    },
    {
      "Title": "Tacun",
      "tags": "restaurant",
      "Likes": 4.2,
      "topLeftText": "",
      "description": "Blvd. Kukulcan KM. 11.5",
      "modalDescription": "Blvd. Kukulcan KM. 11.5",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://tacun.restaurantwebexperts.com/"
    },
    {
      "Title": "Mayan Lounge by Puerto Maya Cancún - Mexican and Mayan Food Restaurant",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 55 9225 2694",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://puertomayacancun.com/best-mexican-food-cancun/"
    },
    {
      "Title": "CAO | Modern Mexican Kitchen in Cancún",
      "tags": "restaurant",
      "Likes": 4.5,
      "topLeftText": "+52 998 427 0525",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://caorestaurante.com.mx/"
    },
    {
      "Title": "Restaurante Lindo Oaxaca Cancun",
      "tags": "restaurant",
      "Likes": 4.5,
      "topLeftText": "+52 998 884 1618",
      "description": "Av Yaxchilán Esquina",
      "modalDescription": "Av Yaxchilán Esquina",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://restaurantelindooaxacacancun.com/"
    },
    {
      "Title": "Restaurante Mextreme",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "+52 998 820 2024",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://mextrememexico.com/"
    },
    {
      "Title": "La Parrilla Cancún",
      "tags": "restaurant",
      "Likes": 4.4,
      "topLeftText": "+52 998 287 8118",
      "description": "Av Yaxchilán 51",
      "modalDescription": "Av Yaxchilán 51",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://laparrilla.com.mx/?utm_source=google&utm_medium=mybusiness"
    },
    {
      "Title": "La Buena Barra",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 313 4211",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "https://labuenabarra.mx/cancun/"
    },
    {
      "Title": "Xkat-Ik",
      "tags": "restaurant",
      "Likes": 4.6,
      "topLeftText": "+52 998 885 3538",
      "description": "Blvd. Kukulcan 77500",
      "modalDescription": "Blvd. Kukulcan 77500",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://xkatik.com/"
    },
    {
      "Title": "Restaurante Hacienda El Mortero",
      "tags": "restaurant",
      "Likes": 4.7,
      "topLeftText": "+52 998 201 5263",
      "description": "Blvd. Kukulcan 9",
      "modalDescription": "Blvd. Kukulcan 9",
      "imageUrl": "https://i.ibb.co/ZJX28LB/cancunrestaurant.png",
      "bottomText": 77500,
      "linkUrl": "http://www.restaurantehaciendaelmortero.com/"
    },
    {
      "Title": "Preferred Luxury Real Estate",
      "tags": "real estate",
      "Likes": 5,
      "topLeftText": "+52 998 293 1591",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "https://www.preferredrealestate.com.mx/"
    },
    {
      "Title": "Eproperties VIP Real Estate",
      "tags": "real estate",
      "Likes": 4.3,
      "topLeftText": "+52 998 146 5154",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "http://www.eproperties.mx/"
    },
    {
      "Title": "PALMA REAL PROPERTIES",
      "tags": "real estate",
      "Likes": 4.5,
      "topLeftText": "+52 998 252 4817",
      "description": "Av. Bonampak ",
      "modalDescription": "Av. Bonampak ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "http://www.palmarealtors.com/"
    },
    {
      "Title": "CENTURY 21 ELITE ADVISORS Real Estate Sale, Rent, & Property Management",
      "tags": "real estate",
      "Likes": 4.5,
      "topLeftText": "+52 998 295 3505",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77560,
      "linkUrl": "https://c21eliteadvisors.com/"
    },
    {
      "Title": "Mexico Real Estate",
      "tags": "real estate",
      "Likes": 4,
      "topLeftText": "+52 984 179 2454",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "https://offplan-mexico.com/"
    },
    {
      "Title": "Cancun Luxury Real Estate",
      "tags": "real estate",
      "Likes": 0,
      "topLeftText": "+52 55 4877 7863",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77506,
      "linkUrl": "http://www.cancunluxuryrealestate.com/"
    },
    {
      "Title": "Inmobiliaria The Brokers Real Estate Cancun",
      "tags": "real estate",
      "Likes": 5,
      "topLeftText": "+52 998 432 4991",
      "description": "Av Tulum 11",
      "modalDescription": "Av Tulum 11",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77504,
      "linkUrl": "https://www.thebrokerscun.com/"
    },
    {
      "Title": "Cancun Estate",
      "tags": "real estate",
      "Likes": 5,
      "topLeftText": "+52 998 884 0608",
      "description": "Av. Puerto Cancun ",
      "modalDescription": "Av. Puerto Cancun ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "http://cancun.estate/"
    },
    {
      "Title": "Cancun Real Estate",
      "tags": "real estate",
      "Likes": 4.6,
      "topLeftText": "+52 998 165 2745",
      "description": "La Costa 116",
      "modalDescription": "La Costa 116",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77509,
      "linkUrl": "https://cancunrealestate.agency/"
    },
    {
      "Title": "Cancun Playa Realty",
      "tags": "real estate",
      "Likes": 5,
      "topLeftText": "+52 998 842 0034",
      "description": "Farallón 12",
      "modalDescription": "Farallón 12",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77505,
      "linkUrl": "http://www.cancunplayarealty.com/"
    },
    {
      "Title": "Puerto Realty",
      "tags": "real estate",
      "Likes": 4.7,
      "topLeftText": "+52 998 688 0710",
      "description": "Av. Puerto Cancun ",
      "modalDescription": "Av. Puerto Cancun ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "https://www.puertorealty.com/"
    },
    {
      "Title": "Luxury Cancun Realty",
      "tags": "real estate",
      "Likes": 4.1,
      "topLeftText": "+52 998 841 4900",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "http://www.luxurycancunrealty.com/"
    },
    {
      "Title": "Keller Williams Breeze Riviera",
      "tags": "real estate",
      "Likes": 4.4,
      "topLeftText": "+52 998 196 4205",
      "description": "Av. Bonampak 11",
      "modalDescription": "Av. Bonampak 11",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "https://www.kwmexico.mx/KWBreezeRiviera"
    },
    {
      "Title": "Caribbean Realtors",
      "tags": "real estate",
      "Likes": 4.7,
      "topLeftText": "+52 998 186 0535",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77504,
      "linkUrl": "http://www.caribbeanrealtors.com.mx/"
    },
    {
      "Title": "Turquesa TD Bienes Raíces",
      "tags": "real estate",
      "Likes": 5,
      "topLeftText": "+52 998 332 5966",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77500,
      "linkUrl": "http://www.turquesatdbienesraices.com/?utm_source=google&utm_medium=wix_google_business_profile&utm_campaign=8517807725759464911"
    },
    {
      "Title": "Cancun Broker Inmobiliario",
      "tags": "real estate",
      "Likes": 4.9,
      "topLeftText": "+52 998 143 4656",
      "description": "Capricornio ",
      "modalDescription": "Capricornio ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77507,
      "linkUrl": "https://www.cancunbrokerinmobiliario.com/"
    },
    {
      "Title": "Dream Lagoons Cancun oficinas",
      "tags": "real estate",
      "Likes": 4.3,
      "topLeftText": "+52 998 841 0165",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/2KWdT5G/cancunrealestate.png",
      "bottomText": 77535,
      "linkUrl": "https://www.propiedadescancun-rivieramaya.com/"
    },
    {
      "Title": "Ap Consultores Cancún",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 55 4452 6915",
      "description": "Av. Puerto Cancun ",
      "modalDescription": "Av. Puerto Cancun ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "https://ap-consultores.com.mx/"
    },
    {
      "Title": "Abogado Cancún",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 577 3806",
      "description": "Cocodrilo 385",
      "modalDescription": "Cocodrilo 385",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77533,
      "linkUrl": "https://www.pinedaasociados.com.mx/"
    },
    {
      "Title": "Notaría Pública Número 95",
      "tags": "legal",
      "Likes": 4.8,
      "topLeftText": "+52 998 626 0168",
      "description": "Av. Contoy ",
      "modalDescription": "Av. Contoy ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77505,
      "linkUrl": "http://www.notaria95cancun.com.mx/"
    },
    {
      "Title": "AXN Asociados, Corporativo Jurídico",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 983 120 5540",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77533,
      "linkUrl": "https://youtube.com/channel/UCXHlGbRqoxW27DUZNfSHCMA"
    },
    {
      "Title": "Mata Law Firm",
      "tags": "legal",
      "Likes": 4.7,
      "topLeftText": "+52 998 419 9083",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "http://www.matalaw.com/"
    },
    {
      "Title": "VIELMA ABOGADOS",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 133 9222",
      "description": "Capricornio 267 B",
      "modalDescription": "Capricornio 267 B",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77507,
      "linkUrl": "http://vielmaabogados.mx/"
    },
    {
      "Title": "Abogados Martínez Soto y Asociados",
      "tags": "legal",
      "Likes": 3,
      "topLeftText": "+52 998 307 4455",
      "description": "Mulsay 25",
      "modalDescription": "Mulsay 25",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77515,
      "linkUrl": "http://abogadoencancun.com.mx/"
    },
    {
      "Title": "Defend Abogados Cancún",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 884 0201",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77509,
      "linkUrl": "http://defendabogados.com/"
    },
    {
      "Title": "Estudio Legal cancún (@MiAbogadodeFamiliaCancun)",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 264 3075",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77510,
      "linkUrl": "https://m.facebook.com/MiAbogadodeFamiliaCancun"
    },
    {
      "Title": "Especialistas en Propiedad Intelectual",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 441 3801",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/Especialistas-en-Propiedad-Intelectual-103128104788277/"
    },
    {
      "Title": "ALAVEZ MORALES AGUIRRE Y ASOCIADOS",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 55 8703 4955",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77508,
      "linkUrl": "https://www.facebook.com/profile.php?id=61550895205434&mibextid=ZbWKwL"
    },
    {
      "Title": "Schutz Legal",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 212 5243",
      "description": "C. Punta Petempich ",
      "modalDescription": "C. Punta Petempich ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77509,
      "linkUrl": "https://schutzlegal.com/"
    },
    {
      "Title": "Lobb y Pellegrini Attorneys Abogados",
      "tags": "legal",
      "Likes": 0,
      "topLeftText": "+52 999 163 5627",
      "description": "Antonio Enríquez Savignac 30",
      "modalDescription": "Antonio Enríquez Savignac 30",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77503,
      "linkUrl": "https://yucatan.legal/"
    },
    {
      "Title": "Mexico Visa Help",
      "tags": "legal",
      "Likes": 3,
      "topLeftText": "+52 55 2319 4868",
      "description": "Manzana 5",
      "modalDescription": "Manzana 5",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "http://www.immigrationhelp.com.mx/"
    },
    {
      "Title": "Iikim Asesores",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 214 8729",
      "description": "Av Sunyaxchen 60",
      "modalDescription": "Av Sunyaxchen 60",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77509,
      "linkUrl": "http://www.iikimasesores.com/"
    },
    {
      "Title": "Ceballos y Asociados",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 884 8542",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77506,
      "linkUrl": "http://www.ceballosyasociados.com/"
    },
    {
      "Title": "JC Abogados",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 180 2464",
      "description": "Xpuhil 11",
      "modalDescription": "Xpuhil 11",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "https://jcabogados.negocio.site/"
    },
    {
      "Title": "Dextrum asesoría legal",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 209 7000",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77533,
      "linkUrl": "https://www.facebook.com/dextreum.dextrum.1"
    },
    {
      "Title": "Abogados en Cancún | M.A. Abogados",
      "tags": "legal",
      "Likes": 4.5,
      "topLeftText": "+52 998 342 9809",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "http://abogadosencancun.com/"
    },
    {
      "Title": "Abogados de Cancún y Contadores de Cancún, Corporativo FSU",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 107 6098",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/Contadores-y-Abogados-de-Canc%C3%BAn-Corporativo-FSU-SC-110738054852683"
    },
    {
      "Title": "QHA | Lawyers Quezada Herrera",
      "tags": "legal",
      "Likes": 4.7,
      "topLeftText": "+52 998 898 2065",
      "description": "Av. Puerto Cancun ",
      "modalDescription": "Av. Puerto Cancun ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "http://qhabogados.com/"
    },
    {
      "Title": "Prax Legis Abogados",
      "tags": "legal",
      "Likes": 4.6,
      "topLeftText": "+52 998 883 9019",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77506,
      "linkUrl": "http://praxislegis.mx/"
    },
    {
      "Title": "Abraham Magaña y Asociados, S. C.",
      "tags": "legal",
      "Likes": 3.9,
      "topLeftText": "+52 998 845 5628",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77508,
      "linkUrl": "http://amabogados.net/"
    },
    {
      "Title": "ESPOSITO & ASOCIADOS LAW FIRM",
      "tags": "legal",
      "Likes": 4.6,
      "topLeftText": "+52 998 604 9510",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "http://esposito.mx/"
    },
    {
      "Title": "Abogados en Cancún-NOVELO,CEN Y GAMBOA",
      "tags": "legal",
      "Likes": 4.6,
      "topLeftText": "+52 998 892 5302",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77517,
      "linkUrl": "http://www.abogadoscancun.com/"
    },
    {
      "Title": "BUREAU Corporativo Legal Services",
      "tags": "legal",
      "Likes": 4.5,
      "topLeftText": "+52 998 884 1797",
      "description": "Relámpago 1",
      "modalDescription": "Relámpago 1",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77505,
      "linkUrl": "http://www.bureau.com.mx/"
    },
    {
      "Title": "ORTIZ AGUILAR & ASOCIADOS",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 561 1111",
      "description": "Eclipse 10-1",
      "modalDescription": "Eclipse 10-1",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77506,
      "linkUrl": "http://www.ortizaguilar.mx/"
    },
    {
      "Title": "INTEGRUM CORPORATIVO JURIDICO",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 989 3182",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/Integrumjuridicocancun/"
    },
    {
      "Title": "iikim Asesores",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "",
      "description": "Ixcun ",
      "modalDescription": "Ixcun ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77508,
      "linkUrl": "http://www.iikimasesores.com/"
    },
    {
      "Title": "Iniestra Abogados",
      "tags": "legal",
      "Likes": 5,
      "topLeftText": "+52 998 884 1601",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/VYhJD8r/cancunlegal.png",
      "bottomText": 77500,
      "linkUrl": "http://iabogados.mx/"
    },
    {
      "Title": "Shiny crystal mexico",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 367 3036",
      "description": "Benito Juárez 510",
      "modalDescription": "Benito Juárez 510",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://shiny-crystal-mexico.negocio.site/?utm_source=gmb&utm_medium=referral"
    },
    {
      "Title": "Joyeria Ciala",
      "tags": "jewelry",
      "Likes": 5,
      "topLeftText": "+52 998 411 1414",
      "description": "Xuencal 33",
      "modalDescription": "Xuencal 33",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77515,
      "linkUrl": "https://www.facebook.com/Cialaoficial"
    },
    {
      "Title": "Eternity joyas",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 366 6262",
      "description": "C. 79 ",
      "modalDescription": "C. 79 ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77516,
      "linkUrl": "https://eternitydiamonds.com.mx/"
    },
    {
      "Title": "Joyería Pink - Malecón",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 385 5653",
      "description": "Av. Bonampak ",
      "modalDescription": "Av. Bonampak ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://pink-joyeria.com/"
    },
    {
      "Title": "Joyería Pandora",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 881 3150 ext. 4275",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://stores.pandora.net/es-mx/mx-roo/cancun/joyeria-pandora-mx0f21eb6b.html"
    },
    {
      "Title": "SÉ JOYA",
      "tags": "jewelry",
      "Likes": 5,
      "topLeftText": "+52 998 191 0847",
      "description": "Av. Cobá 25-01",
      "modalDescription": "Av. Cobá 25-01",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "http://sejoya.com.mx/"
    },
    {
      "Title": "Joyeria Ponce NICE",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 845 3607",
      "description": "C. 4 Pte. ",
      "modalDescription": "C. 4 Pte. ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77536,
      "linkUrl": "https://joyeriafinacancun.com/"
    },
    {
      "Title": "Aleah IP Jewelry",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 137 3324",
      "description": "Av. Sayil 1101A",
      "modalDescription": "Av. Sayil 1101A",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "http://aleahipjewelry.com/"
    },
    {
      "Title": "Tresor Jewelry",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 109 6663",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77534,
      "linkUrl": "https://tresor-jewelry.ueniweb.com/?utm_campaign=gmb"
    },
    {
      "Title": "Tous Jewelry",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 345 1205",
      "description": "Blvd. Kukulcan 1",
      "modalDescription": "Blvd. Kukulcan 1",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://www.tous.com/mx-es/"
    },
    {
      "Title": "Corso Jewelry",
      "tags": "jewelry",
      "Likes": 4.7,
      "topLeftText": "+52 33 3834 1674",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77565,
      "linkUrl": "http://www.corso.mx/"
    },
    {
      "Title": "Nice Cancún",
      "tags": "jewelry",
      "Likes": 4.7,
      "topLeftText": "+52 998 887 6748",
      "description": "Av Xcaret 5",
      "modalDescription": "Av Xcaret 5",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://www.niceonline.com/mx/"
    },
    {
      "Title": "Joyerías BIZZARRO Las Americas Cancun II",
      "tags": "jewelry",
      "Likes": 4.8,
      "topLeftText": "+52 998 415 2964",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "http://www.joyeriasbizzarro.com/"
    },
    {
      "Title": "Cristal Joyas, Las Américas Cancún",
      "tags": "jewelry",
      "Likes": 4.1,
      "topLeftText": "+52 998 887 6185",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77503,
      "linkUrl": "http://www.cristaljoyas.com/"
    },
    {
      "Title": "Beads & Gems Co. Plaza Monarca Cancún",
      "tags": "jewelry",
      "Likes": 4.6,
      "topLeftText": "+52 998 247 4794",
      "description": "Av Xcaret ",
      "modalDescription": "Av Xcaret ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77505,
      "linkUrl": "https://www.facebook.com/beadsandgemsco.cancun"
    },
    {
      "Title": "Premier Joyería y Relojería",
      "tags": "jewelry",
      "Likes": 4.3,
      "topLeftText": "+52 998 884 4070",
      "description": "Av. Tulum Sur 260",
      "modalDescription": "Av. Tulum Sur 260",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "http://www.premierjoyeria.com/"
    },
    {
      "Title": "Platamax Villas Del Mar",
      "tags": "jewelry",
      "Likes": 4.3,
      "topLeftText": "",
      "description": "Av. Tules 51",
      "modalDescription": "Av. Tules 51",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77517,
      "linkUrl": "http://platapormayoreo.com/"
    },
    {
      "Title": "Tous Puerto Cancún",
      "tags": "jewelry",
      "Likes": 4.6,
      "topLeftText": "+52 998 881 3150",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://www.tous.com/"
    },
    {
      "Title": "Joyeria en Cancún | Pink",
      "tags": "jewelry",
      "Likes": 4.8,
      "topLeftText": "+52 998 392 3089",
      "description": "Blvd. Kukulcan km. 1.5",
      "modalDescription": "Blvd. Kukulcan km. 1.5",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://pink-joyeria.com/"
    },
    {
      "Title": "JOYERATI ALMACEN CANCUN",
      "tags": "jewelry",
      "Likes": 4.5,
      "topLeftText": "+52 998 240 4923",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "http://www.joyerati.com.mx/"
    },
    {
      "Title": "Arya Joyas",
      "tags": "jewelry",
      "Likes": 5,
      "topLeftText": "+52 667 730 5599",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77505,
      "linkUrl": "http://www.aryamexico.com/"
    },
    {
      "Title": "Platamor Kabah",
      "tags": "jewelry",
      "Likes": 5,
      "topLeftText": "+52 998 317 3950",
      "description": "Av. Kabah ",
      "modalDescription": "Av. Kabah ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://www.platamor.com/"
    },
    {
      "Title": "Tous Jewelry",
      "tags": "jewelry",
      "Likes": 4.3,
      "topLeftText": "+52 998 345 1205",
      "description": "Av. Bonampak 7",
      "modalDescription": "Av. Bonampak 7",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://www.tous.com/mx-es/"
    },
    {
      "Title": "G Store Joyeria y Accesorios",
      "tags": "jewelry",
      "Likes": 0,
      "topLeftText": "+52 998 222 2382",
      "description": "Calle Av Chilam Balam Local 16",
      "modalDescription": "Calle Av Chilam Balam Local 16",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77533,
      "linkUrl": "https://gstore.odoo.com/shop"
    },
    {
      "Title": "Joyería Pandora",
      "tags": "jewelry",
      "Likes": 4.3,
      "topLeftText": "+52 998 881 3150",
      "description": "Av. Bonampak MZ 27",
      "modalDescription": "Av. Bonampak MZ 27",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://stores.pandora.net/es-mx/mx-roo/cancun/joyeria-pandora-mxb806f353.html?utm_source=google&utm_medium=listing&utm_content=mxb806f353&utm_campaign=MX-ROO&utm_keyword=Cancun"
    },
    {
      "Title": "namastelimx crystal jewelry shop",
      "tags": "jewelry",
      "Likes": 4,
      "topLeftText": "",
      "description": "P.º de Maule 67",
      "modalDescription": "P.º de Maule 67",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77533,
      "linkUrl": "http://www.namasteli.com.mx/"
    },
    {
      "Title": "Joyería Pandora",
      "tags": "jewelry",
      "Likes": 4.6,
      "topLeftText": "+52 998 881 3150 ext. 4330",
      "description": "Blvd. Kukulcan MZ 52",
      "modalDescription": "Blvd. Kukulcan MZ 52",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://stores.pandora.net/es-mx/mx-roo/cancun/joyeria-pandora-mxb3ccbbd7.html?utm_source=google&utm_medium=listing&utm_content=mxb3ccbbd7&utm_campaign=MX-ROO&utm_keyword=Cancun"
    },
    {
      "Title": "Silverson Joyerías Cancún 1",
      "tags": "jewelry",
      "Likes": 3.7,
      "topLeftText": "+52 998 884 8498",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77514,
      "linkUrl": "http://www.joyeriasilverson.com/"
    },
    {
      "Title": "Swarovski",
      "tags": "jewelry",
      "Likes": 4.3,
      "topLeftText": "+52 998 176 8436",
      "description": "Blvd. Kukulcan Km. 12.5",
      "modalDescription": "Blvd. Kukulcan Km. 12.5",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "http://www.swarovski.com/"
    },
    {
      "Title": "Matis Joyería",
      "tags": "jewelry",
      "Likes": 3.2,
      "topLeftText": "",
      "description": "Av. Sayil 30",
      "modalDescription": "Av. Sayil 30",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77503,
      "linkUrl": "https://www.matisjewelry.com/"
    },
    {
      "Title": "Joyería Maraf",
      "tags": "jewelry",
      "Likes": 4.3,
      "topLeftText": "+52 998 884 4858",
      "description": "C. Jurel No",
      "modalDescription": "C. Jurel No",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "http://www.maraf.com/"
    },
    {
      "Title": "Cartier Cancún",
      "tags": "jewelry",
      "Likes": 4.8,
      "topLeftText": "+52 800 227 8437",
      "description": "Blvd. Kukulcan KM 13",
      "modalDescription": "Blvd. Kukulcan KM 13",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://stores.cartier.com/mexico/quintana-roo/cancun/blvd-kukulcan-km-13,-mz-53-lt-8"
    },
    {
      "Title": "Tiffany & Co.",
      "tags": "jewelry",
      "Likes": 4.5,
      "topLeftText": "+52 998 176 8391",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://www.tiffany.com.mx/jewelry-stores/cancun/?local=true&y_source=1_MTgxMjMwNC03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D"
    },
    {
      "Title": "International Jewelry Center & Outlet Shopping Mall",
      "tags": "jewelry",
      "Likes": 4.2,
      "topLeftText": "+52 998 840 6015",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/P44mchk/cancunjewelry.png",
      "bottomText": 77500,
      "linkUrl": "https://www.shoppingcancun.com/"
    },
    {
      "Title": "Pool Bar Flamingo Hotel Las Palmas",
      "tags": "bars",
      "Likes": 4,
      "topLeftText": "+52 998 848 8870",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "http://www.flamingocancun.com/"
    },
    {
      "Title": "Fat Tuesday La Isla",
      "tags": "bars",
      "Likes": 3.8,
      "topLeftText": "",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.fattuesday.com/"
    },
    {
      "Title": "D'Cave",
      "tags": "bars",
      "Likes": 4,
      "topLeftText": "+52 998 883 3333",
      "description": "Km. 9.5 Blvd. Kukulcan",
      "modalDescription": "Km. 9.5 Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "http://www.mandalatickets.com/en/disco/d-cave"
    },
    {
      "Title": "Twin Peaks",
      "tags": "bars",
      "Likes": 4.1,
      "topLeftText": "+52 998 847 1226",
      "description": "7 Av. Bonampak",
      "modalDescription": "7 Av. Bonampak",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77503,
      "linkUrl": "https://twinpeaksmexico.mx/sucursales/cancun"
    },
    {
      "Title": "La Vaquita Cancun",
      "tags": "bars",
      "Likes": 3.5,
      "topLeftText": "+52 998 883 3333",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://mandalatickets.com/en/cancun/disco/la-vaquita"
    },
    {
      "Title": "Bar los 4 Elementos",
      "tags": "bars",
      "Likes": 4.3,
      "topLeftText": "",
      "description": "Av Yaxchilán",
      "modalDescription": "Av Yaxchilán",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://cuatroelementosgroup.com.mx/"
    },
    {
      "Title": "Primo Donceles",
      "tags": "bars",
      "Likes": 4.5,
      "topLeftText": "",
      "description": "Guadalupe Victoria",
      "modalDescription": "Guadalupe Victoria",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77524,
      "linkUrl": "https://instagram.com/primodonceles?igshid=NTdlMDg3MTY="
    },
    {
      "Title": "Juana Margarita",
      "tags": "bars",
      "Likes": 3.8,
      "topLeftText": "+52 998 848 7000",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://cancun.ziva.hyatt.com/en/hotel/dining/bars/juana-margarita-bar.html"
    },
    {
      "Title": "La Vista - Lobby Bar Hotel Solymar",
      "tags": "bars",
      "Likes": 4.3,
      "topLeftText": "+52 998 885 1811",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "http://solymarcancun.com/"
    },
    {
      "Title": "Punta Vista",
      "tags": "bars",
      "Likes": 3.8,
      "topLeftText": "+52 998 848 7000",
      "description": "Manzana 51 Blvd. Kukulcan",
      "modalDescription": "Manzana 51 Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://cancun.ziva.hyatt.com/en/hotel/dining/bars/punta-vista-bar.html"
    },
    {
      "Title": "La Barra",
      "tags": "bars",
      "Likes": 4,
      "topLeftText": "",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.seadustcancun.com/en/gastronomy/la-barra/"
    },
    {
      "Title": "Coco Bongo",
      "tags": "bars",
      "Likes": 4.1,
      "topLeftText": "+52 998 883 2373",
      "description": "30 Blvd. Kukulcan",
      "modalDescription": "30 Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.cocobongo.com/"
    },
    {
      "Title": "Mandala Nightclub",
      "tags": "bars",
      "Likes": 4.4,
      "topLeftText": "+52 998 883 3333",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://mandalatickets.com/en/cancun/disco/mandala"
    },
    {
      "Title": "Congo Bar Cancun",
      "tags": "bars",
      "Likes": 4.2,
      "topLeftText": "+52 998 126 9260",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "http://facebook.com/CongoBarOficial/"
    },
    {
      "Title": "11:11 Club Cancún",
      "tags": "bars",
      "Likes": 4.1,
      "topLeftText": "+52 998 135 2243",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://m.facebook.com/1111club"
    },
    {
      "Title": "Mandala Beach Club",
      "tags": "bars",
      "Likes": 4.5,
      "topLeftText": "+52 998 883 3333",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://mandalatickets.com/en/cancun/disco/mandala-beach"
    },
    {
      "Title": "Barezzito Puerto Cancun",
      "tags": "bars",
      "Likes": 4.4,
      "topLeftText": "+52 998 370 0603",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/barezzitopuertocancun"
    },
    {
      "Title": "MANGOS",
      "tags": "bars",
      "Likes": 4.1,
      "topLeftText": "+52 998 256 6683",
      "description": "17 Tulipanes",
      "modalDescription": "17 Tulipanes",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/mangoscancun"
    },
    {
      "Title": "The City Nightclub Cancun",
      "tags": "bars",
      "Likes": 4.2,
      "topLeftText": "+52 998 883 3333",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://mandalatickets.com/en/cancun/disco/the-city"
    },
    {
      "Title": "El Estadio Cerveceria & Restaurante",
      "tags": "bars",
      "Likes": 4.5,
      "topLeftText": "",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://el-estadio-cerveceria-restaurante.negocio.site/"
    },
    {
      "Title": "Abolengo",
      "tags": "bars",
      "Likes": 4,
      "topLeftText": "",
      "description": "5 Blvd. Kukulcan",
      "modalDescription": "5 Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://mandalatickets.com/en/cancun/disco/abolengo"
    },
    {
      "Title": "Royal Lounge - Cancún",
      "tags": "bars",
      "Likes": 4.2,
      "topLeftText": "+52 998 403 0100",
      "description": "l2 Av. Sayil",
      "modalDescription": "l2 Av. Sayil",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77503,
      "linkUrl": "https://m.facebook.com/RoyalLoungeCancun/"
    },
    {
      "Title": "Las Canoas",
      "tags": "bars",
      "Likes": 4.1,
      "topLeftText": "",
      "description": "1051 C. 16",
      "modalDescription": "1051 C. 16",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77517,
      "linkUrl": "https://www.lascanoasbar.com/"
    },
    {
      "Title": "Estatus Night Club",
      "tags": "bars",
      "Likes": 4.9,
      "topLeftText": "+52 998 392 3231",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://tickets.grupoparty.com/"
    },
    {
      "Title": "La Playita Restaurante Bar Cancún",
      "tags": "bars",
      "Likes": 4.4,
      "topLeftText": "+52 998 561 8153",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/LaPlayitaRestauranteCancun"
    },
    {
      "Title": "La Palapita Tulum",
      "tags": "bars",
      "Likes": 4.5,
      "topLeftText": "",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.lapalapita.mx/"
    },
    {
      "Title": "Fat Tuesday Forum by Sea Plaza",
      "tags": "bars",
      "Likes": 3.9,
      "topLeftText": "",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77501,
      "linkUrl": "https://www.fattuesday.com/"
    },
    {
      "Title": "Dips & Sips",
      "tags": "bars",
      "Likes": 4.8,
      "topLeftText": "",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.hyatt.com/en-US/hotel/mexico/hyatt-ziva-cancun/canif?src=adm_sem_agn_360i_crp_ppc_Brand_Mexico_EN_google_Brand_Mexico_EN_ZV_Mexico_Exact_e_hyatt%20ziva%20mexico_Brand&gclsrc=aw.ds&&src=adm_sem_agn_360i_crp_ppc_Brand_Mexico_EN_google_Brand_Mexico_EN_ZV_Mexico_Exact_{bidmatchtype}_hyatt%20ziva%20mexico_Brand&gclid=CjwKCAjw7anqBRALEiwAgvGgmxEZVOC1VJcAtnAX3iViPVgNxlP8azHscCBG1MC0xNoqteIrozVYRBoCdT0QAvD_BwE"
    },
    {
      "Title": "Glass Bar",
      "tags": "bars",
      "Likes": 3,
      "topLeftText": "+52 998 848 7500",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://oasishoteles.com/es/hoteles/grand-oasis-sens"
    },
    {
      "Title": "Tiki Island Bar Cancún",
      "tags": "bars",
      "Likes": 4.9,
      "topLeftText": "+52 998 161 9588",
      "description": "C. Ciricote",
      "modalDescription": "C. Ciricote",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77533,
      "linkUrl": "https://www.facebook.com/Tikiislandbarcancun"
    },
    {
      "Title": "Route 666 Bikers Bar",
      "tags": "bars",
      "Likes": 4.4,
      "topLeftText": "+52 998 399 5588",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "http://route666bikersbar.com/"
    },
    {
      "Title": "Sigfrido",
      "tags": "bars",
      "Likes": 4.8,
      "topLeftText": "+52 998 217 7517",
      "description": "104 Av Carlos Nader",
      "modalDescription": "104 Av Carlos Nader",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://instagram.com/sigfrido_mx?igshid=1p32297p13tl0"
    },
    {
      "Title": "Monkey Business Cancún",
      "tags": "bars",
      "Likes": 4.5,
      "topLeftText": "+52 998 392 9343",
      "description": "Blvd. Kukulcan",
      "modalDescription": "Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.monkeybusiness.fun/"
    },
    {
      "Title": "Los Aluxes Bar",
      "tags": "bars",
      "Likes": 4.5,
      "topLeftText": "+52 998 290 2326",
      "description": "26 Av Tulum",
      "modalDescription": "26 Av Tulum",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/BarLosAluxesCancun/"
    },
    {
      "Title": "Bar del Mar",
      "tags": "bars",
      "Likes": 4.5,
      "topLeftText": "+52 998 848 7000",
      "description": "7 Lote",
      "modalDescription": "7 Lote",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://cancun.ziva.hyatt.com/en/hotel/dining/bars/bar-del-mar.html"
    },
    {
      "Title": "Cotorritos",
      "tags": "bars",
      "Likes": 4.5,
      "topLeftText": "",
      "description": "Km. 9.5 Blvd. Kukulcan",
      "modalDescription": "Km. 9.5 Blvd. Kukulcan",
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://cotorritos.mx/"
    },
    {
      "Title": "Alebris bar",
      "tags": "bars",
      "Likes": 3.3,
      "topLeftText": "+52 998 883 0031",
      "description": null,
      "modalDescription": null,
      "imageUrl": "https://i.ibb.co/tqs3V7W/cancunbars.png",
      "bottomText": 77500,
      "linkUrl": "https://www.facebook.com/Alebrisbar/"
    },
    {
      "Title": "Reynoso & Navarro Asociados - Asesores Profesionales en Seguros y Fianzas",
      "tags": "insurance",
      "Likes": 5,
      "topLeftText": "+52 998 884 0018",
      "description": "Av. Bonampak 45",
      "modalDescription": "Av. Bonampak 45",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "http://www.reynosonavarro.com/"
    },
    {
      "Title": "Asesores en Seguros Torrealba Guzman",
      "tags": "insurance",
      "Likes": 0,
      "topLeftText": "+52 998 156 6209",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77503,
      "linkUrl": "https://aseguratehoy.saltodigital.mx/"
    },
    {
      "Title": "Quálitas",
      "tags": "insurance",
      "Likes": 3.6,
      "topLeftText": "+52 998 887 3256",
      "description": "Av. Labná ",
      "modalDescription": "Av. Labná ",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "https://www.qualitas.com.mx/"
    },
    {
      "Title": "Agencia de Seguros Cancun",
      "tags": "insurance",
      "Likes": 4.7,
      "topLeftText": "+52 998 410 4091",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77533,
      "linkUrl": "http://agenciaseguroscancun.com/?utm_source=gmb&utm_medium=referral"
    },
    {
      "Title": "Quálitas Seguros",
      "tags": "insurance",
      "Likes": 3.8,
      "topLeftText": "+52 998 884 6959",
      "description": "Av. Cobá 209",
      "modalDescription": "Av. Cobá 209",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77509,
      "linkUrl": "https://www.qualitas.com.mx/"
    },
    {
      "Title": "ANA Seguros",
      "tags": "insurance",
      "Likes": 3.7,
      "topLeftText": "+52 998 884 9825",
      "description": "Av Xcaret 5",
      "modalDescription": "Av Xcaret 5",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "https://anaseguros.com.mx/anaweb/index.html"
    },
    {
      "Title": "Crami Seguros",
      "tags": "insurance",
      "Likes": 0,
      "topLeftText": "+52 998 880 5978",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77533,
      "linkUrl": "http://www.cramiseguros.com/"
    },
    {
      "Title": "Orbe Seguros Cancún",
      "tags": "insurance",
      "Likes": 0,
      "topLeftText": "+52 800 672 3222",
      "description": "Blvd. Kukulcan ",
      "modalDescription": "Blvd. Kukulcan ",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "http://www.orbeseguros.com.mx/"
    },
    {
      "Title": "Seguro de Autos",
      "tags": "insurance",
      "Likes": 0,
      "topLeftText": "+52 998 287 1199",
      "description": "Av Carlos Nader 103",
      "modalDescription": "Av Carlos Nader 103",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "http://segurosdetaxis.com.mx/"
    },
    {
      "Title": "Consultores Integrales Agente de Seguros",
      "tags": "insurance",
      "Likes": 5,
      "topLeftText": "+52 998 887 4049",
      "description": "C Fuego 10",
      "modalDescription": "C Fuego 10",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "https://cbeseguros.com/"
    },
    {
      "Title": "ANA Seguros",
      "tags": "insurance",
      "Likes": 4.9,
      "topLeftText": "+52 998 209 6041",
      "description": "Av. Sayil ",
      "modalDescription": "Av. Sayil ",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "https://anaseguros.com.mx/anaweb/index.html"
    },
    {
      "Title": "Dara Protege - Agencia de Seguros",
      "tags": "insurance",
      "Likes": 5,
      "topLeftText": "+52 998 169 9679",
      "description": "De Porto Príncipe 35",
      "modalDescription": "De Porto Príncipe 35",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77533,
      "linkUrl": "https://daraprotege.com.mx/"
    },
    {
      "Title": "Sekura Oficina Península",
      "tags": "insurance",
      "Likes": 0,
      "topLeftText": "+52 998 800 7675",
      "description": "Av. Bonampak Mz. 1",
      "modalDescription": "Av. Bonampak Mz. 1",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "http://sekura.mx/"
    },
    {
      "Title": "AXA Seguros (Pabellón Norte)",
      "tags": "insurance",
      "Likes": 0,
      "topLeftText": "+52 998 252 6219",
      "description": " ",
      "modalDescription": " ",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77533,
      "linkUrl": "https://gagasesorfinanciero.com/"
    },
    {
      "Title": "Mi Agente Seguro",
      "tags": "insurance",
      "Likes": 4.8,
      "topLeftText": "+52 998 882 0500",
      "description": "Av. Bonampak",
      "modalDescription": "Av. Bonampak",
      "imageUrl": "https://i.ibb.co/L5CVNsP/cancuninsurance.png",
      "bottomText": 77500,
      "linkUrl": "https://miagenteseguro.com.mx/contacto/"
    }
];

// Make it available globally
if (typeof window !== 'undefined') {
  window.directoryData = directoryData;
}

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = directoryData;
}

